spring.application.name=Assignment1

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

# Enable to use virtual threads for testing.
spring.threads.virtual.enabled=true

# Allow to reject 25MB file as it is a maximum of the OpenAi for audio.
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# Allows to use the local OpenAI_API_KEY in local
spring.profiles.active=local